# save flash
CONFIG_MOSH_IPERF3=n
CONFIG_MOSH_SOCK=n
CONFIG_MOSH_PING=n
CONFIG_MOSH_CURL=n
CONFIG_MOSH_GNSS=n
CONFIG_MOSH_PPP=n
CONFIG_MOSH_SMS=n
CONFIG_MOSH_LOCATION=n
CONFIG_MOSH_FOTA=n
CONFIG_MOSH_REST=n
CONFIG_MOSH_CLOUD_REST=n
CONFIG_MOSH_CLOUD_MQTT=n
CONFIG_MOSH_CLOUD_COAP=n
CONFIG_MOSH_CLOUD_LWM2M=n
CONFIG_MOSH_FOTA=n

CONFIG_NRF_CLOUD=n
CONFIG_NRF_CLOUD_AGNSS=n


# Disable NVS settings
CONFIG_NVS=n
CONFIG_SETTINGS_NVS=n
# Enable FCB settings instead
CONFIG_FCB=y
CONFIG_SETTINGS=y
CONFIG_SETTINGS_FCB=y

# Error error zephyr/zephyr_pre0.elf uses VFP register arguments
CONFIG_FP_SOFTABI=y
CONFIG_FPU=y
CONFIG_FPU_SHARING=y

CONFIG_SOFTSIM_DEBUG=y